name: piaui_app
description: A new Flutter project. Created by Slidy

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

## Slidy Scripts
vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  mobx_build: $runner build
  mobx_watch: $clean & $get & $runner watch
  mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  shimmer: ^1.1.2
  dio: ^4.0.0
  http: ^0.13.3
  flutter_session: ^0.1.1
  html: ^0.15.0
  url_launcher: any
  convert: ^3.0.1
  shared_preferences: ^0.5.7+3
  flutter_mobx: ^1.1.0+2
  provider: ^4.1.3
  google_sign_in: ^5.1.0
  mobx: ^1.2.1+4
  flutter_modular: ^2.0.1
  json_annotation: ^3.0.1
  drop_cap_text: ^1.1.3
  intl: ^0.17.0
  flutter_html: ^0.11.1  
  equatable: ^2.0.3
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  # mockito: ^5.0.13
  modular_codegen: any
  mobx_codegen: ^1.1.2
  build_runner: ^1.10.1
  json_serializable: ^3.3.0
  flutter_launcher_icons: "^0.9.2"


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/play_store_512.png"

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/piaui_logo.png
    - assets/images/piaui_devices.png
    - assets/images/icon_configuration.png
    - assets/images/icon_lupa.png
    - assets/images/icon_menu.png
    - assets/images/icon_profile.png
    - assets/images/icon_revista.png
    - assets/images/arrow.png
    - assets/images/arrow-sign.png
    - assets/images/arrow_menu.png
    - assets/images/arrow-left.png
    - assets/images/icon_x.png
    - assets/images/icon_x_config.png
    - assets/images/night-mode.png
    - assets/images/font-size.png

    - assets/images/afogados.png
    - assets/images/agora.png
    - assets/images/assassinos.png
    - assets/images/bolsonaro.png
    - assets/images/debate.png
    - assets/images/diarios.png
    - assets/images/gps.png
    - assets/images/jogo-do-prende.png
    - assets/images/livro.png
    - assets/images/parados.png
    - assets/images/fechado.png

    - assets/images/intenal_article.png
    - assets/images/carrosel_image.png
    - assets/images/allan_abreu.png

    - assets/images/arrow_download.png
    - assets/images/arrow_check.png

    - assets/images/google.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Piaui
      fonts:
        - asset: assets/fonts/PiauiRegular.otf
        - asset: assets/fonts/PiauiBold.otf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
